CMDS = {
    'TAKE_OFF': 'take_off',
    'LAND': 'land',
    'X_DEC': 'x_dec',
    'X_INC': 'x_inc',
    'Y_DEC': 'y_dec',
    'Y_INC': 'y_inc',
    'Z_DEC': 'z_dec',
    'Z_INC': 'z_inc',
    'Z_CW': 'z_cw',
    'Z_CCW': 'z_ccw',
    'FLIP_L': 'flip_l',
    'FLIP_R': 'flip_r',
    'FLIP_F': 'flip_f',
    'FLIP_B': 'flip_b',
    'FLIP_BL': 'flip_bl',
    'FLIP_BR': 'flip_br',
    'FLIP_FL': 'flip_fl',
    'FLIP_FR': 'flip_fr',
    'TRACK': 'track',
    'SENTRY': 'sentry',
    'USER_CONTROL': 'user control',
    'NONE': 'none',
}

DRONE_CMDS = {
    'take_off': 'takeoff',
    'land': 'land',
    'x_dec': 'right',
    'x_inc': 'left',
    'y_dec': 'back',
    'y_inc': 'forward',
    'z_dec': 'down',
    'z_inc': 'up',
    'z_cw': 'cw',
    'z_ccw': 'ccw',
    'flip_l': 'flip l',
    'flip_r': 'flip r',
    'flip_f': 'flip f',
    'flip_b': 'flip b',
    'flip_fl': 'flip fl',
    'flip_fr': 'flip fr',
    'flip_bl': 'flip bl',
    'flip_br': 'flip br',
}
