from tellobot.resolutions import TARGET_FRAME_WIDTH, TARGET_FRAME_HEIGHT

GUI_CENTER_BOX_HALF_SIZE = int(TARGET_FRAME_HEIGHT / 5)
CENTER_POINT = (int(TARGET_FRAME_WIDTH / 2), int(TARGET_FRAME_HEIGHT / 2))
CAMERA_WINDOW = "FLY BOI CAMERA"
UI_WINDOW = "FLY BOI UI"
