# tello
# TARGET_FRAME_WIDTH = 320
# TARGET_FRAME_HEIGHT = 240

# web camera
TARGET_FRAME_WIDTH = 320
TARGET_FRAME_HEIGHT = 240

# mac web camera
# TARGET_FRAME_WIDTH = 640
# TARGET_FRAME_HEIGHT = 480

WEB_CAMERA_FRAME_WIDTH = 320
WEB_CAMERA_FRAME_HEIGHT = 240

TELLO_CAMERA_FRAME_WIDTH = 960
TELLO_CAMERA_FRAME_HEIGHT = 720

